### ISSUE TITLE
Задача на контейнеризацию openpose

### ISSUE THREAD

**Issue by funbotan** [anakham/MIET.AI.Course#2]
[Насколько я вижу, на docker hub полно контейнеров openpose.](https://hub.docker.com/search?q=openpose&type=image) Можно, конечно, реализовать еще один (совершенно точно не списанный), но было бы лучше как-то модифицировать задание, чтобы было интереснее.

**Comment by anakham** [comment]
Да, то, что докеры уже могут быть, я не учёл. Придётся учесть.

Спасибо
